// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Formplug","status":true,"description":"Allows users to give a thumbs up, down or Wiggle to Formbar and interact with Formbar API via socket.io-client.","parameters":{"Formbar URL":"https://formbeta.yorktechapps.com/","API Key":"6eceb85787dbbd54deb02a78e1a271d622e7044ac9b70ea81578f7f8f4ae382b5e7a771725cfec5a1100697b715e8dc84a8ed2e1c9498b52afb5484f264df6b3"}}
];
